### ISSUE TITLE
License

### ISSUE THREAD

**Issue by reppertj** [MarioKrenn6240/SEMNET#2]
I enjoyed the paper and am thinking of using some of its ideas in a personal project. Before I start looking at or potentially using some of the code in this repo, I want to be legally in the clear to do so. Can you consider adding a license?

More info is here:

https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

**Comment by MarioKrenn6240** [comment]
Great point. i added one, thank you!

**Comment by reppertj** [comment]
Awesome, thanks!
