### ISSUE TITLE
Pathnames in Matlab Version

### ISSUE THREAD

**Issue by dbl001** [MarioKrenn6240/SEMNET#4]
I noticed the pathnames in various Matlab files (e.g. FromScratch.m) have Windows style back slashes (e.g. '\').
(I'm running on a Mac).
Also, in the file CreateFullArticleDataAPS.m:

addpath('C:\Users\IQS-1\Dropbox\MetaNetwork\Indizes\jsonlab')

**Comment by MarioKrenn6240** [comment]
Thanks you a lot. Do you mind making a PR that produces a system independent path, i can test it here at a windows machine too.

**Comment by dbl001** [comment]
What is line #30 in CreateFullArticleDataAPS.m supposed to be?  
Something in jsonlab?  Where do I get it?

E.g.
Matlab doesn’t recognize ‘loadjson’.

FullArtInfos  loads([folder3 articleDir(ADi).name]);

**Comment by MarioKrenn6240** [comment]
Check this file provided by mathworks: [loadjson](https://www.mathworks.com/matlabcentral/mlc-downloads/downloads/submissions/55286/versions/1/previews/loadjson.m/index.html). Hope it helps.

**Comment by dbl001** [comment]
Thanks!

Check this out ...

https://blogs.mathworks.com/loren/2007/04/13/machine-independent-filenames/
