### ISSUE TITLE
full articles dataset

### ISSUE THREAD

**Issue by IbtihalFerwana** [MarioKrenn6240/SEMNET#5]
Hi @MarioKrenn6240 
Thanks for making the dataset and code available. 

I'm trying to reproduce the dataset using `create_full_article_data.py` script, but I noticed that the [arxiv xml files](https://github.com/MarioKrenn6240/SEMNET/tree/master/python/1aCreateFullArticleData/arxivAbstractsXML) only include years from 2000 and onwards. Is there a way we get the full article set as used in the pnas paper, from 1919 year, or let me know if I'm missing something. 

Thanks.

**Comment by MarioKrenn6240** [comment]
@IbtihalFerwana This is only a very small subset of the dataset. The full dataset contains all papers from arxiv (you can nowadays download via kaggle) and from APS (you need to apply for access to their metadatabase).

**Comment by IbtihalFerwana** [comment]
I see, thanks for the clarification.
