### ISSUE TITLE
Incorrect cosine similarity calculation in python codes

### ISSUE THREAD

**Issue by garywei944** [MarioKrenn6240/SEMNET#6]
Hello @MarioKrenn6240,

I'm working on my course project and am reading your paper and codes. It's a great idea to consider each node on the graph to be the concept and predict a research trend by doing a link prediction task.

However, when I ran through the python codes, I noticed that [line 41 of calc_properties.py](https://github.com/MarioKrenn6240/SEMNET/blob/master/python/4CalculateAncientNetworks/calc_properties.py#L41) is dividing the dot product by the 	Frobenius norm ([np.linalg.norm doc](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html)) of the single_net to calculate the cosine similarity between the paper i and j.

This is incorrect because the cosine similarity b/w paper i and j should be irrelevant to the other papers and it should be fixed to
```
    cos_sim=dot(single_net, single_net)/(
            norm(single_net, axis=1)[:,None]@norm(single_net, axis=0)[None,:]  # (n, n)
    )
```

The divide here is now element-wise division and the operation is well-defined in numpy.

Could you double-check it?

---

EDIT: Please ignore the pull request. I realized that if I implement the cosine similarity correctly, there are a bunch of cases that the entire row or column of the single_net are all 0, which results in divide by zero issues and the result becomes a bunch of np.nan.
![2022-11-25_20-31](https://user-images.githubusercontent.com/33930674/204067392-7ac09b08-f0f6-40d0-b628-70e196a7ba36.png)

**Comment by garywei944** [comment]
Closed the issue b/c I noticed that it is clarified in Supplementary Information, which wasn't included in [pnas.org](https://www.pnas.org/doi/10.1073/pnas.1914370116). Sorry for bothering you!

**Comment by garywei944** [comment]
Sorry for close and reopening the issue. I thought it twice and believed that the cosine similarity is calculated incorrectly. Could you please review it?

**Comment by MarioKrenn6240** [comment]
Hi @garywei944 Thanks i will check this. I used the MATLAB code in the paper, and translated it to python just for convinience of others. Let me recommend to check [this repo](https://github.com/artificial-scientist-lab/FutureOfAIviaAI), where we extended the current approach and performed a competition, with many people contributing different methods. I hope thats useful for you. Mario
